
import { uniqueId } from 'lodash';

import {
  IconCopy, IconLayoutDashboard, IconMoodHappy, IconTypography,
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconListTree,
  IconLayoutSidebar,
  IconLock, IconAlignBoxLeftBottom, IconCheckbox, IconRadar, IconSlideshow, IconCaretUpDown, IconTable, 
  IconForms,
  IconFriends

} from '@tabler/icons-react';


const Menuitems = [
  {
    navlabel: true,
    subheader: 'Principal',
  },
  {
    id: uniqueId(),
    title: 'Vincula tu música',
    icon: IconAperture,
    href: '/sample-page',
  },
  {
    id: uniqueId(),
    title: 'Resultados',
    icon: IconLayoutDashboard,
    href: '/dashboard',
  },
  {
    navlabel: true,
    subheader: 'Comunidad IA y música - salvando vidas',
  },
  {
    id: uniqueId(),
    title: 'Aportes comunidad ♫',
    icon: IconNotebook,
    href: 'https://flexy-react-main.netlify.app/apps/kanban',
  },
  {
    id: uniqueId(),
    title: 'Aportar ♫',
    icon: IconChartDonut3,
    href: 'None',
    chip: 'Pro',
    children: [
      {
        id: uniqueId(),
        title: 'Mis posts - eliminar o editar',
        icon: IconPoint,
        href: 'https://flexy-react-main.netlify.app/frontend-pages/blog/',
      },
      {
        id: uniqueId(),
        title: 'Nuevo post',
        icon: IconPoint,
        href: 'https://flexy-react-main.netlify.app/apps/notes',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Autenticación & gestión',
  },
  {
    id: uniqueId(),
    title: 'Login',
    icon: IconLogin,
    href: '/auth/login',
  },
  {
    id: uniqueId(),
    title: 'Register',
    icon: IconUserCircle,
    href: '/auth/register',
  },
  {
    id: uniqueId(),
    title: 'Usuario/Doctor',
    icon: IconLock,
    href: '/auth/login',
    chip: 'Pro',
    children: [
      {
        id: uniqueId(),
        title: 'Paciente',
        icon: IconRotate,
        href: 'None',
        chip: 'Pro',
        children: [
          {
            id: uniqueId(),
            title: 'Recomendaciones',
            icon: IconPoint,
            href: 'https://play.google.com/store/apps/details?id=com.google.android.apps.tasks&hl=es_CO',
            chip: 'Pro',
          },
          {
            id: uniqueId(),
            title: 'Musicoterapia',
            icon: IconPoint,
            href: 'https://open.spotify.com/playlist/5xXpUY3henFlcPt86jJrqh?si=3381489ce8b2496a',
            chip: 'Pro',
          },
           {
            id: uniqueId(),
            title: 'Citas disponibles',
            icon: IconPoint,
            href: 'https://flexy-react-main.netlify.app/apps/calendar',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Cool doctor 8)',
        icon: IconZoomCode,
        href: 'None',
        disabled: 'True',
        children: [
                {
                  id: uniqueId(),
                  title: 'Mis pacientes',
                  icon: IconChartCandle,
                  href: 'https://excel.cloud.microsoft/es-es/',
                  disabled: 'True',
                },
                {
                  id: uniqueId(),
                  title: 'Seguimiento',
                  icon: IconTicket,
                  href: 'https://flexy-react-main.netlify.app/apps/tickets',
                  disabled: 'True',
                },
                {
                  id: uniqueId(),
                  title: 'Citas próximas',
                  icon: IconChartDonut3,
                  href: 'https://calendar.google.com/calendar/u/0/r?pli=1',
                  disabled: 'True',
                },
        ],
      },
    ]
  },
  {
    id: uniqueId(),
    title: 'Plan +',
    icon: IconCurrencyDollar,
    href: 'https://flexy-react-main.netlify.app/pages/pricing',
    chip: '50% OFF!',
  },
  {
    id: uniqueId(),
    title: 'Configuración de cuenta',
    icon: IconUserCircle,
    href: 'https://flexy-react-main.netlify.app/pages/account-settings',
  },
  {
    navlabel: true,
    subheader: 'Extra y próximas funcionalidades',
  },
  {
    id: uniqueId(),
    title: 'Centro de atención cercano',
    icon: IconBan,
    href: 'https://www.google.com/maps/@4.6376269,-74.1122391,15z?entry=ttu&g_ep=EgoyMDI1MDUyMS4wIKXMDSoASAFQAw%3D%3D',
    disabled: true,
  },
  {
    id: uniqueId(),
    title: 'EAN contigo',
    icon: IconFriends,
    href: 'https://universidadean.edu.co/estudiantes/ean-contigo',
  },
  {
    id: uniqueId(),
    title: 'FAQ',
    icon: IconHelp,
    href: 'https://universidadean.edu.co/atencion-psicosocial',
  },
  {
    id: uniqueId(),
    title: 'Acerca de nosotros',
    external: true,
    icon: IconStar,
    href: 'https://www.linkedin.com/in/dayana-velasquez-alvarez-672752360/',
  },

];

export default Menuitems;
